@BASE_URL = http://localhost:8888
@USER_TOKEN = {{user_login.response.body.token}}
@DOCTOR_TOKEN = {{doctor_login.response.body.token}}

### doctor register
POST {{BASE_URL}}/auth/register/doctor
Content-Type: application/json

{
  "username": "coke",
  "password": "bb",
  "specialization": "obgyn"
}

### user register
POST {{BASE_URL}}/auth/register/user
Content-Type: application/json

{
  "username": "hera",
  "password": "cc"
}

### doctor login
# @name doctor_login
POST {{BASE_URL}}/auth/login/doctor
Content-Type: application/json

{
  "username": "natp",
  "password": "doctor"
}

### user login
# @name user_login
POST {{BASE_URL}}/auth/login/user
Content-Type: application/json

{
  "username": "hera",
  "password": "cc"
}

###  get user me
GET {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

###  update user me
PUT {{BASE_URL}}/users/me
Authorization: Bearer {{USER_TOKEN}}
Content-Type: application/json

{
  "username": "hera2",
  "password": "cc"
}

### doctor get me
GET {{BASE_URL}}/doctors/me
Content-Type: application/json
Authorization: Bearer {{DOCTOR_TOKEN}}

### doctor update me
PUT {{BASE_URL}}/doctors/me
Authorization: Bearer {{DOCTOR_TOKEN}}
Content-Type: application/json

{
  "username": "dr. nat",
  "password": "gg",
  "specialization": "psychologist"
}