@BASE_URL = http://localhost:8888

### doctor register
POST {{BASE_URL}}/auth/register/doctor
Content-Type: application/json

{
  "username": "coke",
  "password": "bb",
  "specialization": "obgyn"
}

### user register
POST {{BASE_URL}}/auth/register/user
Content-Type: application/json

{
  "username": "hera",
  "password": "cc"
}

### doctor login
POST {{BASE_URL}}/auth/login/doctor
Content-Type: application/json

{
  "username": "natp",
  "password": "doctor"
}

### user login
POST {{BASE_URL}}/auth/login/user
Content-Type: application/json

{
  "username": "ben",
  "password": "cc"
}

### user get me
GET {{BASE_URL}}/users/me
Content-Type: application/json

{
  "username": "ben",
  "password": "cc"
}



